[build]
  # This is the directory Netlify will serve your static files from.
  publish = "public"
  # This is the directory where your serverless function is located.
  functions = "functions"

# Increase function timeout for GEMS API calls (GEMS can be very slow)
# and set the bundler.
[functions]
  timeout = 120
  node_bundler = "esbuild"

# Rule for the unsubscribe page to handle dynamic IDs
[[redirects]]
  from = "/unsubscribe/*"
  to = "/unsubscribe.html"
  status = 200

# Cache GEMS images at CDN level
[[headers]]
  for = "/api/gems/*/image"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"
    
# Cache other API responses briefly
[[headers]]
  for = "/api/data"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=300"

[[headers]]
  for = "/api/complete"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=300"