[build]
  # This is the directory Netlify will serve your static files from.
  publish = "public"
  # This is the directory where your serverless function is located.
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200